### PR TITLE
PATCH: com_github_scionproto_scion/snet_less_allocs.patch

### PR DESCRIPTION
**Pull request by lukedirtwalker**
snet: add options to do less allocations

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anapaya/os-scion/7)

### CODE REVIEW

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anapaya/os-scion/7)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @oncilla and @shitz)

___
*[`pkg/snet/packet_conn.go` line 120 at r1](https://reviewable.io/reviews/Anapaya/os-scion/7#-Ny-N9hH2taKeWCTRlqH:-Ny-N9hH2taKeWCTRlqI:bmw34bi) ([raw file](https://github.com/Anapaya/os-scion/blob/e7ed687d9ced78629c2e3a6021f49afc31bfd3f6/pkg/snet/packet_conn.go#L120)):*
> ```Go
> 	// SerializeOpts can be used to customize the serialization of packets sent
> 	// with this connection. Only use this if you know what you are doing.
> 	SerializeOpts []SerializeOption
> ```

I wonder if we should just always set those. and not expose them. But it would be risky if someone does concurrent Writes.

**Review by oncilla — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anapaya/os-scion/7)* status: all files reviewed, 3 unresolved discussions (waiting on @lukedirtwalker and @shitz)

___
*[`pkg/snet/packet.go` line 348 at r1](https://reviewable.io/reviews/Anapaya/os-scion/7#-Ny-MteN-R9MV8lr4agC:-Ny-MteN-R9MV8lr4agD:b-7mfffi) ([raw file](https://github.com/Anapaya/os-scion/blob/e7ed687d9ced78629c2e3a6021f49afc31bfd3f6/pkg/snet/packet.go#L348)):*
> ```Go
> type DecodeOpts func(*decodeOpts)
> 
> // IgnorePath is an option to ignore the path when decoding a packet. This means
> ```

Given that we want to shave off allocations, does the optional functions pattern not force us to do some allocations?

Naively, I would think that both IgnorePath allocates, due to being a closure, and the var args, due to being a slice.

It probably also forces the decodeOpts to escape to the heap.

I think in this instance, where Decode is invoked very often, it might be better to go with a config struct.
___
*[`pkg/snet/packet.go` line 562 at r1](https://reviewable.io/reviews/Anapaya/os-scion/7#-Ny-P6fX2AxSpxGjcbFR:-Ny-P6fX2AxSpxGjcbFS:bz9ngjb) ([raw file](https://github.com/Anapaya/os-scion/blob/e7ed687d9ced78629c2e3a6021f49afc31bfd3f6/pkg/snet/packet.go#L562)):*
> ```Go
> }
> 
> type serializeOpt struct {
> ```

Same observation.
___
*[`pkg/snet/packet_conn.go` line 120 at r1](https://reviewable.io/reviews/Anapaya/os-scion/7#-Ny-N9hH2taKeWCTRlqH:-Ny-PBFgBhnE5IMo5RpC:b-d4sayu) ([raw file](https://github.com/Anapaya/os-scion/blob/e7ed687d9ced78629c2e3a6021f49afc31bfd3f6/pkg/snet/packet_conn.go#L120)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I wonder if we should just always set those. and not expose them. But it would be risky if someone does concurrent Writes.
</blockquote></details>

Let's be defensive.

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anapaya/os-scion/7)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @oncilla and @shitz)

___
*[`pkg/snet/packet.go` line 348 at r1](https://reviewable.io/reviews/Anapaya/os-scion/7#-Ny-MteN-R9MV8lr4agC:-Ny-YCsn10rYInOKvex5:b-896fix) ([raw file](https://github.com/Anapaya/os-scion/blob/e7ed687d9ced78629c2e3a6021f49afc31bfd3f6/pkg/snet/packet.go#L348)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Given that we want to shave off allocations, does the optional functions pattern not force us to do some allocations?

Naively, I would think that both IgnorePath allocates, due to being a closure, and the var args, due to being a slice.

It probably also forces the decodeOpts to escape to the heap.

I think in this instance, where Decode is invoked very often, it might be better to go with a config struct.
</blockquote></details>

Done.
___
*[`pkg/snet/packet.go` line 562 at r1](https://reviewable.io/reviews/Anapaya/os-scion/7#-Ny-P6fX2AxSpxGjcbFR:-Ny-YCDW2JGnAPFlsUpq:b-896fix) ([raw file](https://github.com/Anapaya/os-scion/blob/e7ed687d9ced78629c2e3a6021f49afc31bfd3f6/pkg/snet/packet.go#L562)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Same observation.
</blockquote></details>

Done.

**Review by oncilla — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anapaya/os-scion/7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shitz)

**Review by lukedirtwalker — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anapaya/os-scion/7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shitz)

**Pull request merged**
